### ISSUE TITLE
After Place an order redrect to cart page and customer session destroy

### ISSUE THREAD

**Issue by magento2demo** [paytabscom/paytabs-magento2.x#25]
Hello, 

we are using the Magento commerce 2.4.3-p1 commerce cloud version. we are not allowing guest checkout so when we plan an order success page not showing and redirect to the cart page. and customer logout also.

Please check and provide patch.

**Comment by armindoPR** [comment]
Hi,

i've implmented the https://github.com/paytabscom/paytabs-magento2.x/pull/27/commits/b7020bd4657632882fe66c3318e1dc2d5c6832da changes...but still get the error that the customer session is lost.

Can you please help me solve that ?

Regards

**Comment by wajihkm** [comment]
Hi,

The logout issue is a known issue on Magento2 since the browsers started to change the default SameSite cookie setting.

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/mc-41359-magento-patch-missing-settings-samesite-cookie-param.html?lang=en

https://github.com/magento/magento2/issues/26377

We have implemented a workaround since version **3.9.1**
Kindly update and let us know if you still face any problems.


Regards,
Wajih
