### ISSUE TITLE
The logger file "debug_paytabs.log" is accessible directly from "pub" directory

### ISSUE THREAD

**Issue by arsalanworld** [paytabscom/paytabs-magento2.x#40]
### Problem:
The logger file `debug_paytabs.log` is downloadable from "pub" directory and we do not find it anywhere inside the `var ` folder.

### Expected Result:
The `debug_paytabs.log` logger file should not be accessible directly from web link and should be created inside `var` directory instead.

### Actual Result:
The `debug_paytabs.log` file is being created at `pub` directory instead and is downloadable directly from website.

### Paytabs Version: `3.7.5`

**Comment by wajihkm** [comment]
Thanks @arsalanworld  for taking this time to check and mention this case.

But actually this part of code should not be called in Magento2 since there should be a Logger object.
This part of the code is usable for fallback cases where the e-commerce system have not defined the `paytabs_error_log` function.
However, the mentioned code has a typo (we already defined the full path to the log file `define('PAYTABS_DEBUG_FILE', 'var/log/debug_paytabs.log');` on Line 8)
Will fix it in the next release.

Regards,
Wajih
